// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of sweeping one cache directory.
 */
export type CacheDirPruneReport = { files_scanned: number, files_deleted: number, bytes_before: number, bytes_freed: number, };
