// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheDirPruneReport } from "./CacheDirPruneReport";

/**
 * Result of sweeping both media caches.
 */
export type CachePruneReport = { filmstrip: CacheDirPruneReport, thumbnails: CacheDirPruneReport, };
