// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KaraokeOptions } from "./KaraokeOptions";

/**
 * Persisted export preferences for sidecar text format + burn-in style.
 * Stored per-project; sane defaults so it's always valid on first use.
 */
export type ExportConfig = { 
/**
 * Default sidecar format: "srt" | "vtt" | "ass"
 */
format: string, 
/**
 * Whether to add captions as burn-in when using a platform preset.
 */
burn_in: boolean, 
/**
 * Caption font size in px (16 / 20 / 24 / 28).
 */
caption_size_px: number, 
/**
 * Caption text colour: "white" | "yellow" | "green"
 */
caption_color: string, 
/**
 * Caption background: "black" | "semitransparent" | "none"
 */
caption_background: string, 
/**
 * Maximum characters per caption line: 32 | 42 | 52
 */
max_chars_per_line: number, 
/**
 * Karaoke (per-word `\k` highlighting) settings for the ASS sidecar AND
 * every burn-in path. Persisted here — not on `Style` — because this is
 * the container that already carries burn-in preferences, so the sidecar
 * export, the final render and the preview proxy all read one value and
 * cannot disagree.
 *
 * `Option` + `#[serde(default)]` so pre-E4a `.sundayedit` files (and the
 * existing frontend `ExportConfig` literals) stay valid; `None` means the
 * same thing as `KaraokeOptions::disabled()`.
 */
karaoke?: KaraokeOptions, };
