// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stretch of empty time on one track. `end_ms` is exclusive.
 *
 * `protected` means a ripple stops here (the clip that follows is locked).
 * Returned by `detect_gaps` — this is a query result, never persisted.
 */
export type Gap = { start_ms: number, end_ms: number, protected: boolean, };
