// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KaraokeStyle } from "./KaraokeStyle";

/**
 * Persisted karaoke settings. Lives on `ExportConfig` (the per-project
 * container that already persists burn-in styling), so the sidecar `.ass`,
 * the final burn-in and the preview proxy all read the SAME values.
 */
export type KaraokeOptions = { 
/**
 * Off by default — enabling it changes every Dialogue line.
 */
enabled: boolean, style: KaraokeStyle, 
/**
 * Colour of not-yet-sung text — becomes the ASS SecondaryColour.
 * Hex `#RRGGBB`; invalid values fall back to white (`hex_to_ass_bgr`).
 */
pending_color: string, 
/**
 * Tint low-confidence words with an inline `\c` override. OFF by default:
 * surfacing uncertainty is an EDITOR affordance, and baking it into the
 * delivered video is a deliberate choice, not a surprise.
 */
confidence_tint: boolean, 
/**
 * Words below this 0–100 confidence get the tint. Default 70 — the
 * tier-2 floor from `docs/CALIBRATION.md`.
 */
confidence_threshold: number, 
/**
 * Hex `#RRGGBB` used for tinted (low-confidence) words.
 */
low_confidence_color: string, };
