// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One karaoke-timed word: the derived (gap-closed) span plus the ASS
 * centisecond duration that `{\k}` / `{\kf}` consumes.
 *
 * `duration_cs` is NOT `round((end_ms - start_ms) / 10)` — see the module
 * docs. It is the step of a cumulative centisecond ladder anchored on the
 * caption's own ASS timestamps, so `sum(duration_cs)` is exactly the Dialogue
 * span in centiseconds.
 */
export type KaraokeWord = { text: string, start_ms: number, end_ms: number, 
/**
 * ASS centiseconds for this word's `\k` step.
 */
duration_cs: number, 
/**
 * 0–100 ASR confidence, carried through for confidence tinting.
 */
confidence: number, };
