// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether one pooled `MediaItem`'s file is still where the project says it is.
 *
 * Returned by the `check_media_paths` command, which the renderer runs on
 * project open so a moved/renamed source shows the relink affordance instead
 * of a silent "Video utilgjengelig" preview and a failing export.
 */
export type MediaAvailability = { media_id: string, path: string, exists: boolean, };
