// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One addressed tile — everything the frontend needs to look it up in its
 * cache and, on a miss, ask the backend to render it.
 */
export type TileRef = { tier: number, index: number, start_ms: number, end_ms: number, key: string, };
