// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a word sits relative to the playhead. The canvas overlay MUST mirror
 * this predicate exactly — it is the visual contract between preview and
 * burn-in.
 */
export type WordState = "pending" | "active" | "done";
